// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djhqfgcsxfukeemvxfzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqaHFmZ2NzeGZ1a2VlbXZ4ZnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTY2NTEsImV4cCI6MjA2OTI3MjY1MX0._PGvVb7mVWmK9VXvdpVdLSSFWoGN9K42pE9dUxn6uPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});